# -*- coding: utf-8 -*-
"""bostonTensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1My1DLVbfLLlaHPZIDC44MNy8DrcKjop3
"""

# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

# 독립변수, 종속변수 분리
# 꼭 분리후에 shape 써서 확인해보기
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax','ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

# 모델의 구조를 만든다.
x = tf.keras.layers.Input(shape=[13])
y = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(x,y)
model.compile(loss='mse')

# 3.데이터로 모델을 학습(FIT)합니다.
#model.fit(독립, 종속, epochs=10)
#model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

# 모델을 이용합니다.
# ':' slicing
model.predict(독립[5:10])

종속[5:10]

# 모델의 수식 확인
model.get_weights()

